# Update the version tag below when you need to change the DataKit version
# Get the latest version from your TrueWatch Platform workspace settings

FROM pubrepo.truewatch.com/datakit/datakit:1.86.0

EXPOSE 9529
